apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: davidathompsonpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: davidathompsonpipelinesjavascriptdocker 
    spec:
      containers:
        - name: davidathompsonpipelinesjavascriptdocker 
          image: dttestacr.azurecr.io/davidathompsonpipelinesjavascriptdocker
          ports:
          - containerPort: 8080